/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author pipetorrendell
 */
public class VentanaRegistroEditorial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistroEditorial
     */
    private DefaultTableModel modeloTablaEditoriales;

    public VentanaRegistroEditorial() {
        initComponents();
        modeloTablaEditoriales = new DefaultTableModel(new String[]{"Nombre", "País de Origen"}, 0);
        tblTablaEditoriales.setModel(modeloTablaEditoriales);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void actualizarTablaEditoriales(String nombre, String pais) {
        modeloTablaEditoriales.addRow(new Object[]{nombre, pais});
    }

    private void guardarEditorial(java.awt.event.ActionEvent evt) {
        String nombreEditorial = txtNombreEditorial.getText().trim();
        String paisOrigen = txtPaisEditorial.getText().trim();
        // Validación y almacenamiento de la editorial
        if (!nombreEditorial.isEmpty() && !paisOrigen.isEmpty()) {
            actualizarTablaEditoriales(nombreEditorial, paisOrigen);
            txtNombreEditorial.setText("");
            txtPaisEditorial.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistroEditorial = new javax.swing.JPanel();
        jblTituloRegistroEditoriales = new javax.swing.JLabel();
        jlbNombreEditorial = new javax.swing.JLabel();
        jlbPaisEditorial = new javax.swing.JLabel();
        txtNombreEditorial = new javax.swing.JTextField();
        txtPaisEditorial = new javax.swing.JTextField();
        btnGuardarEditorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaEditoriales = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Editoriales");

        jblTituloRegistroEditoriales.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jblTituloRegistroEditoriales.setText("Registro de Editoriales");

        jlbNombreEditorial.setText("Nombre del Editorial");

        jlbPaisEditorial.setText("Pais de Origen");

        txtPaisEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisEditorialActionPerformed(evt);
            }
        });

        btnGuardarEditorial.setText("Guardar");
        btnGuardarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEditorialActionPerformed(evt);
            }
        });

        tblTablaEditoriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Pais de Origen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTablaEditoriales);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistroEditorialLayout = new javax.swing.GroupLayout(jPanelRegistroEditorial);
        jPanelRegistroEditorial.setLayout(jPanelRegistroEditorialLayout);
        jPanelRegistroEditorialLayout.setHorizontalGroup(
            jPanelRegistroEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroEditorialLayout.createSequentialGroup()
                .addGroup(jPanelRegistroEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroEditorialLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jblTituloRegistroEditoriales))
                    .addGroup(jPanelRegistroEditorialLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanelRegistroEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegistroEditorialLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelRegistroEditorialLayout.createSequentialGroup()
                                        .addComponent(jlbPaisEditorial)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPaisEditorial))
                                    .addGroup(jPanelRegistroEditorialLayout.createSequentialGroup()
                                        .addComponent(jlbNombreEditorial)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombreEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65)
                                .addComponent(btnGuardarEditorial)))))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroEditorialLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(92, 92, 92))
        );
        jPanelRegistroEditorialLayout.setVerticalGroup(
            jPanelRegistroEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroEditorialLayout.createSequentialGroup()
                .addGroup(jPanelRegistroEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroEditorialLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jblTituloRegistroEditoriales)
                        .addGap(46, 46, 46)
                        .addGroup(jPanelRegistroEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNombreEditorial)
                            .addComponent(txtNombreEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRegistroEditorialLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnGuardarEditorial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistroEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPaisEditorial)
                    .addComponent(txtPaisEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnVolver)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistroEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistroEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaisEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisEditorialActionPerformed

    private void btnGuardarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEditorialActionPerformed
        guardarEditorial(evt);
    }//GEN-LAST:event_btnGuardarEditorialActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VentanaMenu menu = new VentanaMenu(); 
        menu.setVisible(true); 
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroEditorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarEditorial;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanelRegistroEditorial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblTituloRegistroEditoriales;
    private javax.swing.JLabel jlbNombreEditorial;
    private javax.swing.JLabel jlbPaisEditorial;
    private javax.swing.JTable tblTablaEditoriales;
    private javax.swing.JTextField txtNombreEditorial;
    private javax.swing.JTextField txtPaisEditorial;
    // End of variables declaration//GEN-END:variables
}
