
package Interfaz;

import Dominio.Genero;
import Dominio.Sistema;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pipetorrendell
 */
public class VentanaRegistroGenero extends javax.swing.JFrame {

    private Sistema sistema;
    private DefaultListModel<String> modeloListaGeneros;

    /**
     * Creates new form VentanaRegistroGenero
     */
    public VentanaRegistroGenero(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        modeloListaGeneros = new DefaultListModel<>();
        lstGeneros.setModel(modeloListaGeneros);

        // Cargar géneros existentes en la lista
        sistema.getGeneros().forEach(genero
                -> modeloListaGeneros.addElement(genero.getNombre() + "-" + genero.getDescripcion())
        );
    }

    private void actualizarListaGeneros(String nombre, String descripcion) {
        modeloListaGeneros.addElement(nombre + "-" + descripcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jblTituloRegistroGeneros = new javax.swing.JLabel();
        jlbNombreGenero = new javax.swing.JLabel();
        txtNombreGenero = new javax.swing.JTextField();
        jlbDescripcionGenero = new javax.swing.JLabel();
        btnGuardarGenero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGeneros = new javax.swing.JList<>();
        btnVolverMenu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcionGenero = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Registro Generos");

        jblTituloRegistroGeneros.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jblTituloRegistroGeneros.setText("Registro de Generos");

        jlbNombreGenero.setText("Nombre");

        jlbDescripcionGenero.setText("Descripcion");

        btnGuardarGenero.setText("Guardar");
        btnGuardarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarGeneroActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstGeneros);

        btnVolverMenu.setText("Volver");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        txtDescripcionGenero.setColumns(20);
        txtDescripcionGenero.setRows(5);
        txtDescripcionGenero.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDescripcionGeneroPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(txtDescripcionGenero);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnGuardarGenero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbDescripcionGenero)
                    .addComponent(jlbNombreGenero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jblTituloRegistroGeneros)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(btnVolverMenu)))
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jblTituloRegistroGeneros)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombreGenero)
                    .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbDescripcionGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                .addComponent(btnGuardarGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverMenu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        VentanaMenu menu = new VentanaMenu(sistema);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnGuardarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarGeneroActionPerformed
        String nombre = txtNombreGenero.getText().trim();
        String descripcion = txtDescripcionGenero.getText().trim();

        if (nombre.isEmpty() || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar ambos campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (sistema.guardarGenero(nombre, descripcion)) {
            JOptionPane.showMessageDialog(this, "Género registrado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            actualizarListaGeneros(nombre, descripcion);
            txtNombreGenero.setText("");
            txtDescripcionGenero.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "El género ya existe o los datos son inválidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Guardar datos en archivo
        sistema.saveData("data/sistema.ser");
    }//GEN-LAST:event_btnGuardarGeneroActionPerformed

    private void txtDescripcionGeneroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDescripcionGeneroPropertyChange
        txtDescripcionGenero.setLineWrap(true);
        txtDescripcionGenero.setWrapStyleWord(true);

    }//GEN-LAST:event_txtDescripcionGeneroPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sistema sistema = Sistema.loadData("data/sistema.ser");
                new VentanaRegistroGenero(sistema).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarGenero;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jblTituloRegistroGeneros;
    private javax.swing.JLabel jlbDescripcionGenero;
    private javax.swing.JLabel jlbNombreGenero;
    private javax.swing.JList<String> lstGeneros;
    private javax.swing.JTextArea txtDescripcionGenero;
    private javax.swing.JTextField txtNombreGenero;
    // End of variables declaration//GEN-END:variables
}
