package Interfaz;

import Dominio.Libro;
import Dominio.Sistema;
import Dominio.Venta;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pipetorrendell
 * @author nicholasdavies
 */
public class VentanaVentaRegistro extends javax.swing.JFrame {

    private Sistema sistema;
    DefaultListModel<String> modeloLibros = new DefaultListModel<>();
    DefaultListModel<String> modeloVenta = new DefaultListModel<>();
    Map<Libro, Integer> librosSeleccionados = new HashMap<>();

    /**
     * Creates new form VentanaVentaRegistro
     */
    public VentanaVentaRegistro(Sistema sistema) {
        this.sistema = sistema;
        initComponents();
        inicializarListaLibros();
        inicializarNumeroFactura();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void inicializarListaLibros() {
        modeloLibros.clear(); // Limpiar modelo antes de llenarlo
        List<Libro> librosOrdenados = new ArrayList<>(sistema.getLibros());
        librosOrdenados.sort(Comparator.comparing(Libro::getTitulo)); // Ordenar por título
        for (Libro libro : librosOrdenados) {
            modeloLibros.addElement(libro.getIsbn() + " - " + libro.getTitulo() + " (Stock: " + libro.getStock() + ")");
        }

        lstLibros.setModel(modeloLibros);
    }

    private void actualizarListaVenta() {
        modeloVenta.clear();
        double total = 0.0;

        for (Map.Entry<Libro, Integer> entry : librosSeleccionados.entrySet()) {
            Libro libro = entry.getKey();
            int cantidad = entry.getValue();
            double subtotal = libro.getPrecioVenta() * cantidad;
            total += subtotal;

            modeloVenta.addElement(libro.getTitulo() + " - Cantidad: " + cantidad + " - Total: $" + subtotal);
        }
        lstVenta.setModel(modeloVenta);
        txtTotal.setText(String.format("%.2f", total));
    }

    private void inicializarNumeroFactura() {
        int numeroFactura = sistema.getUltimoNumeroFactura() + 1;
        txtNumeroFactura.setText(String.valueOf(numeroFactura));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentaRegistro = new javax.swing.JPanel();
        lblNumeroFactura = new javax.swing.JLabel();
        jblTituloRegistroVentas = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();
        lblFechaVenta = new javax.swing.JLabel();
        txtFechaVenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtClienteVenta = new javax.swing.JTextField();
        lblLibrosLista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLibros = new javax.swing.JList<>();
        lblVentaLista = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstVenta = new javax.swing.JList<>();
        btnAgregarLibro = new javax.swing.JButton();
        btnQuitarLibro = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnRegistrarVenta = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Registro de Venta");

        lblNumeroFactura.setText("Factura");

        jblTituloRegistroVentas.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jblTituloRegistroVentas.setText("Registro de Ventas");
        jblTituloRegistroVentas.setToolTipText("");

        txtNumeroFactura.setEditable(false);
        txtNumeroFactura.setText("1");
        txtNumeroFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroFacturaActionPerformed(evt);
            }
        });

        lblFechaVenta.setText("Fecha");

        txtFechaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        txtClienteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteVentaActionPerformed(evt);
            }
        });

        lblLibrosLista.setText("Libros");

        jScrollPane1.setViewportView(lstLibros);

        lblVentaLista.setText("Venta");

        jScrollPane2.setViewportView(lstVenta);

        btnAgregarLibro.setText("->");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnQuitarLibro.setText("<-");
        btnQuitarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarLibroActionPerformed(evt);
            }
        });

        lblTotal.setText("Total:");

        txtTotal.setEditable(false);

        btnRegistrarVenta.setText("Registrar");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        btnVolverMenu.setText("Volver");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentaRegistroLayout = new javax.swing.GroupLayout(jPanelVentaRegistro);
        jPanelVentaRegistro.setLayout(jPanelVentaRegistroLayout);
        jPanelVentaRegistroLayout.setHorizontalGroup(
            jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jblTituloRegistroVentas))
                    .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                                .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLibrosLista)
                                    .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnQuitarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVentaLista)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                                        .addComponent(lblTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVentaRegistroLayout.createSequentialGroup()
                                .addComponent(lblNumeroFactura)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                                .addComponent(lblFechaVenta)
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtClienteVenta)))))
                .addGap(57, 57, 57))
            .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnRegistrarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverMenu)
                .addGap(148, 148, 148))
        );
        jPanelVentaRegistroLayout.setVerticalGroup(
            jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jblTituloRegistroVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroFactura)
                    .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaVenta)
                    .addComponent(txtFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibrosLista)
                    .addComponent(lblVentaLista))
                .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanelVentaRegistroLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanelVentaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarVenta)
                    .addComponent(btnVolverMenu))
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVentaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVentaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVentaActionPerformed

    private void txtClienteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteVentaActionPerformed

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        int index = lstLibros.getSelectedIndex();
        if (index >= 0) {
            String libroInfo = modeloLibros.get(index);
            String isbn = libroInfo.split(" - ")[0]; // Extraer ISBN
            Libro libro = sistema.buscarLibroPorIsbn(isbn);

            if (libro != null) {
                if (libro.getStock() <= 0) {
                    JOptionPane.showMessageDialog(this, "No hay stock disponible para este libro.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                librosSeleccionados.put(libro, librosSeleccionados.getOrDefault(libro, 0) + 1);
                actualizarListaVenta();
            }
        }
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void btnQuitarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarLibroActionPerformed
        int index = lstVenta.getSelectedIndex();
        if (index >= 0) {
            String ventaInfo = modeloVenta.get(index);
            String titulo = ventaInfo.split(" - ")[0];

            for (Map.Entry<Libro, Integer> entry : librosSeleccionados.entrySet()) {
                if (entry.getKey().getTitulo().equals(titulo)) {
                    if (entry.getValue() > 1) {
                        librosSeleccionados.put(entry.getKey(), entry.getValue() - 1);
                    } else {
                        librosSeleccionados.remove(entry.getKey());
                    }
                    break;
                }
            }
            actualizarListaVenta();
        }
    }//GEN-LAST:event_btnQuitarLibroActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        VentanaMenu menu = new VentanaMenu(sistema);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        if (librosSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe agregar al menos un libro a la venta.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String fecha = txtFechaVenta.getText();
        String cliente = txtClienteVenta.getText();

        if (fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo de fecha vacio o no es una fecha", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Map<Libro, Integer> librosConStock = new HashMap<>();
        List<String> mensajesStock = new ArrayList<>();

        for (Map.Entry<Libro, Integer> entry : librosSeleccionados.entrySet()) {
            Libro libro = entry.getKey();
            int cantidadSeleccionada = entry.getValue();
            int stockDisponible = libro.getStock();

            if (stockDisponible >= cantidadSeleccionada) {
                librosConStock.put(libro, cantidadSeleccionada);
            } else if (stockDisponible > 0) {
                librosConStock.put(libro, stockDisponible);
                mensajesStock.add("El libro \"" + libro.getTitulo() + "\" solo tiene " + stockDisponible + " unidades disponibles.");
            } else {
                mensajesStock.add("El libro \"" + libro.getTitulo() + "\" no tiene stock disponible.");
                continue; // Salta al siguiente libro
            }
        }

        if (librosConStock.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay stock suficiente para realizar la venta.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!mensajesStock.isEmpty()) {
            String mensaje = String.join("\n", mensajesStock);
            JOptionPane.showMessageDialog(this, mensaje, "Stock ajustado", JOptionPane.WARNING_MESSAGE);
        }

        // Generar el número de factura solo si hay libros válidos para la venta
        int numeroFactura = sistema.generarNumeroFactura();
        Venta nuevaVenta = new Venta(numeroFactura, fecha, cliente, librosConStock);

        // Registrar la venta en el sistema
        if (!sistema.registrarVenta(nuevaVenta)) {
            JOptionPane.showMessageDialog(this, "No se pudo registrar la venta debido a un error interno.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Venta registrada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Limpiar selección y campos
        librosSeleccionados.clear();
        actualizarListaVenta();
        txtFechaVenta.setText("");
        txtClienteVenta.setText("");

        // Actualizar lista de libros y número de factura
        inicializarNumeroFactura();
        inicializarListaLibros();
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void txtNumeroFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sistema sistema = Sistema.loadData("data/sistema.ser");
                new VentanaVentaRegistro(sistema).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnQuitarLibro;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelVentaRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jblTituloRegistroVentas;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblLibrosLista;
    private javax.swing.JLabel lblNumeroFactura;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVentaLista;
    private javax.swing.JList<String> lstLibros;
    private javax.swing.JList<String> lstVenta;
    private javax.swing.JTextField txtClienteVenta;
    private javax.swing.JTextField txtFechaVenta;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
