/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package Interfaz;

/**
 *
 * @author pipetorrendell
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuRegistros = new javax.swing.JMenu();
        VentanaRegistroAutor = new javax.swing.JMenuItem();
        VentanaRegistroLibro = new javax.swing.JMenuItem();
        VentanaRegistroEditorial = new javax.swing.JMenuItem();
        VentanaRegistroGenero = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        VentanaVentaRegistro = new javax.swing.JMenuItem();
        VentanaVentaAnular = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        VentanaConsultaLibro = new javax.swing.JMenuItem();
        VentanaConsultaVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Librerías - Realizado por: Felipe Torrendell 302851 - Nicholas Davies 282236");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        menuRegistros.setMnemonic('f');
        menuRegistros.setText("Registros");

        VentanaRegistroAutor.setMnemonic('o');
        VentanaRegistroAutor.setText("Registro de Autor");
        VentanaRegistroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaRegistroAutorActionPerformed(evt);
            }
        });
        menuRegistros.add(VentanaRegistroAutor);

        VentanaRegistroLibro.setMnemonic('x');
        VentanaRegistroLibro.setText("Registro de Libro");
        VentanaRegistroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaRegistroLibroActionPerformed(evt);
            }
        });
        menuRegistros.add(VentanaRegistroLibro);

        VentanaRegistroEditorial.setMnemonic('s');
        VentanaRegistroEditorial.setText("Registro de Editorial");
        VentanaRegistroEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaRegistroEditorialActionPerformed(evt);
            }
        });
        menuRegistros.add(VentanaRegistroEditorial);

        VentanaRegistroGenero.setMnemonic('a');
        VentanaRegistroGenero.setText("Registro de Genero");
        VentanaRegistroGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaRegistroGeneroActionPerformed(evt);
            }
        });
        menuRegistros.add(VentanaRegistroGenero);

        menuBar.add(menuRegistros);

        menuVentas.setMnemonic('h');
        menuVentas.setText("Ventas");

        VentanaVentaRegistro.setMnemonic('c');
        VentanaVentaRegistro.setText("Registrar Venta");
        VentanaVentaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaVentaRegistroActionPerformed(evt);
            }
        });
        menuVentas.add(VentanaVentaRegistro);

        VentanaVentaAnular.setMnemonic('a');
        VentanaVentaAnular.setText("Anular Venta");
        VentanaVentaAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaVentaAnularActionPerformed(evt);
            }
        });
        menuVentas.add(VentanaVentaAnular);

        menuBar.add(menuVentas);

        menuConsultas.setMnemonic('e');
        menuConsultas.setText("Consultas");

        VentanaConsultaLibro.setMnemonic('t');
        VentanaConsultaLibro.setText("Consulta de Libro");
        VentanaConsultaLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaConsultaLibroActionPerformed(evt);
            }
        });
        menuConsultas.add(VentanaConsultaLibro);

        VentanaConsultaVenta.setMnemonic('y');
        VentanaConsultaVenta.setText("Consulta de Ventas");
        VentanaConsultaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaConsultaVentaActionPerformed(evt);
            }
        });
        menuConsultas.add(VentanaConsultaVenta);

        menuBar.add(menuConsultas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VentanaRegistroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaRegistroLibroActionPerformed
        VentanaRegistroLibro ventanaLibro = new VentanaRegistroLibro();
        ventanaLibro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentanaRegistroLibroActionPerformed

    private void VentanaRegistroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaRegistroAutorActionPerformed
        VentanaRegistroAutor ventanaAutor = new VentanaRegistroAutor();
        ventanaAutor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentanaRegistroAutorActionPerformed

    private void VentanaRegistroEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaRegistroEditorialActionPerformed
        VentanaRegistroEditorial ventanaEditorial = new VentanaRegistroEditorial();
        ventanaEditorial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentanaRegistroEditorialActionPerformed

    private void VentanaRegistroGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaRegistroGeneroActionPerformed
        VentanaRegistroGenero ventanaGenero = new VentanaRegistroGenero();
        ventanaGenero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentanaRegistroGeneroActionPerformed

    private void VentanaConsultaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaConsultaLibroActionPerformed
        VentanaConsultaLibro ventanaConsultaLibro = new VentanaConsultaLibro();
        ventanaConsultaLibro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentanaConsultaLibroActionPerformed

    private void VentanaConsultaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaConsultaVentaActionPerformed
        VentanaConsultaVentas ventanaConsultaVentas = new VentanaConsultaVentas();
        ventanaConsultaVentas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentanaConsultaVentaActionPerformed

    private void VentanaVentaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaVentaRegistroActionPerformed
        VentanaVentaRegistro ventanaVenta = new VentanaVentaRegistro();
        ventanaVenta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentanaVentaRegistroActionPerformed

    private void VentanaVentaAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaVentaAnularActionPerformed
        VentanaVentaAnular ventanaAnular = new VentanaVentaAnular();
        ventanaAnular.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VentanaVentaAnularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem VentanaConsultaLibro;
    private javax.swing.JMenuItem VentanaConsultaVenta;
    private javax.swing.JMenuItem VentanaRegistroAutor;
    private javax.swing.JMenuItem VentanaRegistroEditorial;
    private javax.swing.JMenuItem VentanaRegistroGenero;
    private javax.swing.JMenuItem VentanaRegistroLibro;
    private javax.swing.JMenuItem VentanaVentaAnular;
    private javax.swing.JMenuItem VentanaVentaRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenu menuVentas;
    // End of variables declaration//GEN-END:variables

}
